name: 'os2loop_config'
type: module
description: 'OS2Loop Config'
# Used only for development and testing.
hidden: true
core_version_requirement: ^9
package: 'OS2Loop'

# https://www.drupal.org/node/2087879
